import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiNodedotjs,
  SiReact,
  SiAdobe,
    SiRedux,
  SiExpress,
  SiTypescript,
  SiTestinglibrary,
  SiSelenium,
  SiJest,
  SiCucumber,
  SiJenkins,
  SiGithubactions,
  SiGit,
  SiNpm,
  SiFirebase,
  SiHeroku,
  SiGraphql,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiGoogleanalytics,
  SiJirasoftware,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  adobe: SiAdobe,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  node: SiNodedotjs,
  react: SiReact,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  redux: SiRedux,
  express: SiExpress,
  typescript: SiTypescript,
  playwright: SiTestinglibrary,
  selenium: SiSelenium,
  jest: SiJest,
  cucumber: SiCucumber,
  jenkins: SiJenkins,
  githubactions: SiGithubactions,
  git: SiGit,
  npm: SiNpm,
  firebase: SiFirebase,
  heroku: SiHeroku,
  graphql: SiGraphql,
  html5: SiHtml5,
  css3: SiCss3,
  bootstrap: SiBootstrap,
  jira: SiJirasoftware, // If you want a Jira-specific icon, use SiJira from react-icons/si
  googleanalytics: SiGoogleanalytics,
  test: SiJest,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
